flowchart TD


subgraph Demo
a[1]
end
subgraph node4 [4]
v['World!']
end
subgraph node1 [1]
b['Hello']
end

subgraph node2 [2]
        C[45]
end

subgraph node3  ['foo']

G["['A', 'B', 'C', '1']"]
end




Demo-->node4
Demo-->node1
node1-->node2
node2-->node3