flowchart TD


subgraph root [sample.PetsD]
a[3]
end
subgraph node1 [1]
H["['''',''Whiskers'',''Cat'',3]"]
end
subgraph node2 [2]
D["['''',''Fido'',''Dog'',5]"]
end
subgraph node3 [3]
G["['''',''Bugs'',''Rabbit'',95]"]
end






root-->node1
root-->node2
root-->node3
